name: release

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  manifest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.43.1
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}/manifests
          # Return single tag
          flavor: latest=false
      - run: kustomize build config/default > manifest.yaml
      - run: oras push "$TAG" manifest.yaml
        env:
          TAG: ${{ steps.metadata.outputs.tags }}
